[package]
name = "satva-arrow"
description = "Columnar batches and vectorized kernels for Satva pipelines"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
readme.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
satva-types.workspace = true
satva-expr.workspace = true
