[package]
name = "satva-cli"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
satva-core = { path = "../satva-core" }
satva-io = { path = "../satva-io"}
satva-types = { path = "../satva-types"}
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
serde.workspace = true
serde_yaml = "0.9"
