[package]
name = "satva-cli"
description = "Command-line interface for Satva data pipelines"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
readme.workspace = true
keywords.workspace = true
categories = ["command-line-utilities"]

[[bin]]
name = "satva"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
satva-core.workspace = true
satva-runner.workspace = true
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
