[package]
name = "satva-runner"
description = "Load and run Satva pipelines from YAML"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
readme.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_yaml = "0.9"
satva-core.workspace = true
satva-io.workspace = true
satva-parser.workspace = true
satva-types.workspace = true
