[package]
name = "satva-benchmarks"
description = "Criterion benchmarks for Satva"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
satva-expr.workspace = true
satva-parser.workspace = true
satva-types.workspace = true
satva-core.workspace = true
satva-io.workspace = true
satva-arrow.workspace = true
satva-execution.workspace = true
serde_json = "1"
anyhow.workspace = true

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "evaluator"
harness = false

[[bench]]
name = "pipeline"
harness = false
